remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "dark" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"

title: "Xaba Cadabra"
description: "Xaba Cadabra è un blog colmo di recensioni e speculazioni caustiche riguardo Videogiochi, Serie TV, Fumetti e tutte quelle robe nerd."
locale: it

breadcrumbs: true